#nullable enable

namespace DarciControl.Logic.Packaging;

/// <summary>
/// The launcher that ships INSIDE a distributable, generated for the target OS.
///
/// <para>Generated rather than copied, because the repo's own <c>Start-DARCI.ps1</c> cannot work here and
/// fails in a way the builder would never notice: it resolves <c>DARCI-v4/Darci.Api</c> - a path that does
/// not exist in a zip - and starts the core with <c>dotnet run</c>, which needs the SDK the self-contained
/// publish exists to make unnecessary. Shipping it verbatim hands the recipient a launcher that cannot
/// launch, on a machine where they have no way to tell why.</para>
///
/// <para>Both scripts do the same three things: point the core at what shipped beside it, warn (never fail)
/// about a missing Ollama or unpulled model, and run the published executable. Kept in ASCII on purpose -
/// Windows PowerShell 5.1 reads a .ps1 as ANSI without a BOM, and mojibake inside a script is a parse
/// error on the recipient's machine rather than a cosmetic blemish.</para>
///
/// <para><b>The Linux script is UNVERIFIED.</b> It is written for correctness and ships with its executable
/// bit set, but this machine is Windows and it has never been run. Treat it as needing a first-boot check.</para>
/// </summary>
public static class PackagedStartScript
{
    public static string FileNameFor(TargetPlatform platform) => platform.LauncherFileName;

    public static string Build(TargetPlatform platform, string apiUrl = "http://localhost:5081") =>
        platform.IsLinux ? BuildShell(platform, apiUrl) : BuildPowerShell(platform, apiUrl);

    // ---- Windows ----

    private static string BuildPowerShell(TargetPlatform platform, string apiUrl) => $$"""
        # Start-DARCI.ps1 - packaged launcher (Windows)
        #
        # Generated by the DARCI control centre for THIS distributable's layout. The core here is a
        # self-contained build: you do not need the .NET SDK.

        param(
            [switch]$NoBrowser
        )

        $ErrorActionPreference = "Stop"
        $Root    = $PSScriptRoot
        $CoreExe = Join-Path $Root "core\{{platform.ExecutableName}}"
        $ApiUrl  = "{{apiUrl}}"
        $AppUrl  = "$ApiUrl/app/"

        if (-not (Test-Path $CoreExe)) {
            Write-Error "Could not find the core at $CoreExe. Is this distributable complete?"
            exit 1
        }

        # Point the core at what shipped beside it, rather than whatever a previous install left behind.
        $env:DARCI_NODES_PATH   = Join-Path $Root "nodes"
        $env:DARCI_HOST_PROFILE = Join-Path $Root "host-profile.json"
        if (-not $env:DARCI_DB_PATH) {
            $env:DARCI_DB_PATH = Join-Path $Root "Data\darci.db"
        }

        # --- Ollama ---
        # A warning, never a hard stop: the core starts without Ollama, it just cannot think.
        $ollamaUrl = if ($env:DARCI_OLLAMA_BASE_URL) { $env:DARCI_OLLAMA_BASE_URL } else { "http://localhost:11434" }
        $ollamaUp = $false
        try {
            $tags = Invoke-RestMethod -Uri "$ollamaUrl/api/tags" -TimeoutSec 5
            $ollamaUp = $true
        } catch {
            Write-Warning "Ollama is not reachable at $ollamaUrl."
            Write-Warning "Install it from https://ollama.com and run 'ollama serve'. DARCI will start, but its language features will be degraded."
        }

        if ($ollamaUp) {
            # Derived from the host-profile.json in THIS zip - never a hardcoded list.
            $resolver = Join-Path $Root "Get-DarciRequiredModels.ps1"
            if (Test-Path $resolver) {
                $required  = & $resolver -ProfilePath $env:DARCI_HOST_PROFILE
                $installed = $tags.models | ForEach-Object { $_.name }
                foreach ($m in $required) {
                    $have = $installed | Where-Object { $_ -eq $m -or $_ -eq "${m}:latest" -or $_ -like "${m}:*" }
                    if (-not $have) {
                        Write-Warning "Model '$m' is not pulled. Run: ollama pull $m"
                    }
                }
            }
        }

        # --- Knowledge graph ---
        # Neo4j is optional. Configured-but-unreachable is handled by the core, which logs a warning and
        # falls back to SQLite rather than failing to start.
        if (Test-Path (Join-Path $Root ".env.local")) {
            Write-Host "  Using .env.local for optional configuration." -ForegroundColor DarkGray
        } else {
            Write-Host "  Knowledge graph: SQLite (no .env.local - this is a valid setup)." -ForegroundColor DarkGray
        }

        Write-Host ""
        Write-Host "  Starting DARCI on $ApiUrl" -ForegroundColor Cyan
        Write-Host "  Web UI:  $AppUrl" -ForegroundColor Cyan
        Write-Host ""

        if (-not $NoBrowser) {
            Start-Job -ArgumentList $ApiUrl, $AppUrl -ScriptBlock {
                param($ReadyUrl, $BrowserUrl)
                for ($i = 0; $i -lt 90; $i++) {
                    try {
                        $r = Invoke-WebRequest -Uri "$ReadyUrl/status" -UseBasicParsing -TimeoutSec 2 -ErrorAction Stop
                        if ($r.StatusCode -ge 200 -and $r.StatusCode -lt 500) { Start-Process $BrowserUrl; return }
                    } catch {}
                    Start-Sleep -Seconds 1
                }
            } | Out-Null
        }

        # Blocks until Ctrl+C.
        & $CoreExe --urls $ApiUrl
        """;

    // ---- Linux ----

    private static string BuildShell(TargetPlatform platform, string apiUrl) => $$"""
        #!/usr/bin/env bash
        # start-darci.sh - packaged launcher (Linux)
        #
        # Generated by the DARCI control centre for THIS distributable's layout. The core here is a
        # self-contained build: you do not need the .NET SDK.
        #
        # NOTE: generated on a Windows machine and NOT YET RUN ON LINUX. If something here is wrong it is
        # wrong in an obvious way - this is plain bash and safe to edit.

        set -u

        ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
        CORE="$ROOT/core/{{platform.ExecutableName}}"
        API_URL="{{apiUrl}}"

        if [ ! -f "$CORE" ]; then
            echo "Could not find the core at $CORE. Is this distributable complete?" >&2
            exit 1
        fi

        # A zip does not always preserve the executable bit; restore it rather than failing cryptically.
        [ -x "$CORE" ] || chmod +x "$CORE" 2>/dev/null || true

        # Point the core at what shipped beside it, rather than whatever a previous install left behind.
        export DARCI_NODES_PATH="$ROOT/nodes"
        export DARCI_HOST_PROFILE="$ROOT/host-profile.json"
        : "${DARCI_DB_PATH:=$ROOT/Data/darci.db}"
        export DARCI_DB_PATH

        # --- Ollama ---
        # A warning, never a hard stop: the core starts without Ollama, it just cannot think.
        OLLAMA_URL="${DARCI_OLLAMA_BASE_URL:-http://localhost:11434}"
        if command -v curl >/dev/null 2>&1 && curl -sf --max-time 5 "$OLLAMA_URL/api/tags" >/dev/null 2>&1; then
            TAGS="$(curl -sf --max-time 5 "$OLLAMA_URL/api/tags")"
            # Model names come from host-profile.json - never a hardcoded list. Parsed without jq so the
            # script depends on nothing beyond curl.
            REQUIRED="$(grep -o '"model"[[:space:]]*:[[:space:]]*"[^"]*"' "$DARCI_HOST_PROFILE" \
                        | sed 's/.*"\([^"]*\)"$/\1/' | sort -u)"
            for m in $REQUIRED; do
                if ! printf '%s' "$TAGS" | grep -q "\"$m\(:[^\"]*\)\{0,1\}\""; then
                    echo "WARNING: model '$m' is not pulled. Run: ollama pull $m" >&2
                fi
            done
        else
            echo "WARNING: Ollama is not reachable at $OLLAMA_URL." >&2
            echo "         Install it from https://ollama.com and run 'ollama serve'." >&2
            echo "         DARCI will start, but its language features will be degraded." >&2
        fi

        # --- Knowledge graph ---
        # Neo4j is optional. Configured-but-unreachable is handled by the core, which logs a warning and
        # falls back to SQLite rather than failing to start.
        if [ -f "$ROOT/.env.local" ]; then
            echo "  Using .env.local for optional configuration."
        else
            echo "  Knowledge graph: SQLite (no .env.local - this is a valid setup)."
        fi

        echo ""
        echo "  Starting DARCI on $API_URL"
        echo "  Web UI:  $API_URL/app/"
        echo ""

        # Blocks until Ctrl+C.
        exec "$CORE" --urls "$API_URL"
        """;
}
