#nullable enable

namespace DarciControl.Logic.Packaging;

/// <summary>
/// The launcher that ships INSIDE a distributable.
///
/// <para>Generated rather than copied, because the repo's own <c>Start-DARCI.ps1</c> cannot work here and
/// fails in a way the builder would never notice: it resolves <c>DARCI-v4\Darci.Api</c> - a path that does
/// not exist in a zip - and starts the core with <c>dotnet run</c>, which needs the SDK the self-contained
/// publish exists to make unnecessary. Shipping it verbatim hands the recipient a launcher that cannot
/// launch, on a machine where they have no way to tell why.</para>
///
/// <para>So the zip gets a script written for the zip's own layout: run the published executable, point the
/// core at the node folder and host profile that shipped beside it, and check prerequisites using the same
/// derived model list the core itself will apply.</para>
/// </summary>
public static class PackagedStartScript
{
    public const string FileName = "Start-DARCI.ps1";

    public static string Build(string apiUrl = "http://localhost:5081") => $$"""
        # Start-DARCI.ps1 - packaged launcher
        #
        # Generated by the DARCI control centre for THIS distributable's layout. The core here is a
        # self-contained build: you do not need the .NET SDK.

        param(
            [switch]$NoBrowser
        )

        $ErrorActionPreference = "Stop"
        $Root    = $PSScriptRoot
        $CoreExe = Join-Path $Root "core\Darci.Api.exe"
        $ApiUrl  = "{{apiUrl}}"
        $AppUrl  = "$ApiUrl/app/"

        if (-not (Test-Path $CoreExe)) {
            Write-Error "Could not find the core at $CoreExe. Is this distributable complete?"
            exit 1
        }

        # Point the core at what shipped beside it, rather than whatever a previous install left behind.
        $env:DARCI_NODES_PATH   = Join-Path $Root "nodes"
        $env:DARCI_HOST_PROFILE = Join-Path $Root "host-profile.json"
        if (-not $env:DARCI_DB_PATH) {
            $env:DARCI_DB_PATH = Join-Path $Root "Data\darci.db"
        }

        # --- Ollama ---
        # A warning, never a hard stop: the core starts without Ollama, it just cannot think.
        $ollamaUrl = if ($env:DARCI_OLLAMA_BASE_URL) { $env:DARCI_OLLAMA_BASE_URL } else { "http://localhost:11434" }
        $ollamaUp = $false
        try {
            $tags = Invoke-RestMethod -Uri "$ollamaUrl/api/tags" -TimeoutSec 5
            $ollamaUp = $true
        } catch {
            Write-Warning "Ollama is not reachable at $ollamaUrl."
            Write-Warning "Install it from https://ollama.com and run 'ollama serve'. DARCI will start, but its language features will be degraded."
        }

        if ($ollamaUp) {
            # Derived from the host-profile.json in THIS zip - never a hardcoded list.
            $resolver = Join-Path $Root "Get-DarciRequiredModels.ps1"
            if (Test-Path $resolver) {
                $required  = & $resolver -ProfilePath $env:DARCI_HOST_PROFILE
                $installed = $tags.models | ForEach-Object { $_.name }
                foreach ($m in $required) {
                    $have = $installed | Where-Object { $_ -eq $m -or $_ -eq "${m}:latest" -or $_ -like "${m}:*" }
                    if (-not $have) {
                        Write-Warning "Model '$m' is not pulled. Run: ollama pull $m"
                    }
                }
            }
        }

        # --- Knowledge graph ---
        # Neo4j is optional. Configured-but-unreachable is handled by the core, which logs a warning and
        # falls back to SQLite rather than failing to start.
        $envLocal = Join-Path $Root ".env.local"
        if (Test-Path $envLocal) {
            Write-Host "  Using .env.local for optional configuration." -ForegroundColor DarkGray
        } else {
            Write-Host "  Knowledge graph: SQLite (no .env.local - this is a valid setup)." -ForegroundColor DarkGray
        }

        Write-Host ""
        Write-Host "  Starting DARCI on $ApiUrl" -ForegroundColor Cyan
        Write-Host "  Web UI:  $AppUrl" -ForegroundColor Cyan
        Write-Host ""

        if (-not $NoBrowser) {
            Start-Job -ArgumentList $ApiUrl, $AppUrl -ScriptBlock {
                param($ReadyUrl, $BrowserUrl)
                for ($i = 0; $i -lt 90; $i++) {
                    try {
                        $r = Invoke-WebRequest -Uri "$ReadyUrl/status" -UseBasicParsing -TimeoutSec 2 -ErrorAction Stop
                        if ($r.StatusCode -ge 200 -and $r.StatusCode -lt 500) { Start-Process $BrowserUrl; return }
                    } catch {}
                    Start-Sleep -Seconds 1
                }
            } | Out-Null
        }

        # Blocks until Ctrl+C.
        & $CoreExe --urls $ApiUrl
        """;
}
